//! WARNING
//! This code was generated by an AI model.
//! Code may not behave as intended.
//! Please review and test thoroughly.

import React, { useState, useEffect } from "react";
import CodeMirror from "@uiw/react-codemirror";
import { xml } from "@codemirror/lang-xml";
import { XMLValidator } from "fast-xml-parser";

export default function XmlEditor({
    value = "<root></root>",
    onChange = () => { },
    height = "11in",
}) {
    const [text, setText] = useState(value);
    const [error, setError] = useState(null);

    useEffect(() => {
        setText(value);
    }, [value]);

    function handleChange(val) {
        setText(val);
        onChange(val);

        const validation = XMLValidator.validate(val);

        if (validation === true) {
            setError(null);
        } else {
            setError(validation);
        }
    }

    return (
        <div>
            <CodeMirror
                className="codemirror"
                value={text}
                height={height}
                extensions={[xml()]}
                onChange={handleChange}
            />
        </div>
    );
}
